name: instaui
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chewie: ^1.0.2
  video_player: ^2.8.1
  youtube_player_flutter: ^8.1.2
  webview_flutter: ^3.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/motive.mp4
  fonts:
    - family: Fontspring-DEMO-blue_vinyl_regular_ps_ot
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-blue_vinyl_regular_ps_ot.otf
